# Generated by Django 3.1.2 on 2020-11-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20201114_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(default='Ziaur Rahman Joy', max_length=200),
            preserve_default=False,
        ),
    ]
